bitfireAT/icsx5

app/src/main/java/at/bitfire/icsdroid/PermissionUtils.kt, app/src/main/java/at/bitfire/icsdroid/ui/AddCalendarActivity.kt, app/src/main/java/at/bitfire/icsdroid/ui/CalendarListActivity.kt
Fix startup crash, by registering the permission launcher in onCreate (instead of callback) and before view is loaded.
=> New permissions system (fixup)

app/src/main/java/at/bitfire/icsdroid/ui/EditCalendarActivity.kt, app/src/main/res/values/strings.xml
Prevent crash if trying to load non existent calendar, by catching exception, notifying user and finishing activity. Maybe there is a better way?
=> Prevent crash if trying to load non existent calendar (closes #17)

app/build.gradle, app/src/androidTest/java/at/bitfire/icsdroid/CalendarFetcherTest.kt, app/src/androidTest/java/at/bitfire/icsdroid/ui/AddCalendarValidationFragmentTest.kt, app/src/main/java/at/bitfire/icsdroid/ui/AddCalendarValidationFragment.kt, app/src/main/java/at/bitfire/icsdroid/ui/ResourceInfo.kt
Not finished yet. Still needs fallback support for `X-APPLE-COLOR`.
Also tests are failing because changes in ical4android are not included.
=> Add support for COLOR property (closes icsx5#31)

app/src/main/res/xml/network_security.xml
Fixes #43
As per https://developer.android.com/training/articles/security-config
Previous behaviour: only validated certificates in the system certificate
authority store
New behaviour: validates against both system CAs and user-installed CAs
=> Allow use of user-installed CAs

app/src/main/java/at/bitfire/icsdroid/PermissionUtils.kt, app/src/main/java/at/bitfire/icsdroid/ui/AddCalendarActivity.kt, app/src/main/java/at/bitfire/icsdroid/ui/CalendarListActivity.kt
=> First calendar addition doesn't refresh the list

app/src/main/java/at/bitfire/icsdroid/ui/AddCalendarDetailsFragment.kt
Changed threading of all View Models so they don't have any callbacks, just states are used.
Relates to #110
=> Database UI threading

app/src/main/java/at/bitfire/icsdroid/PermissionUtils.kt, app/src/main/java/at/bitfire/icsdroid/ProcessEventsTask.kt, app/src/main/java/at/bitfire/icsdroid/SyncAdapter.kt, app/src/main/java/at/bitfire/icsdroid/SyncWorker.kt, app/src/main/java/at/bitfire/icsdroid/db/dao/CredentialsDao.kt, app/src/main/java/at/bitfire/icsdroid/db/dao/SubscriptionsDao.kt, app/src/main/java/at/bitfire/icsdroid/db/entity/Credential.kt, app/src/main/java/at/bitfire/icsdroid/ui/AddCalendarActivity.kt, app/src/main/java/at/bitfire/icsdroid/ui/AddCalendarDetailsFragment.kt, app/src/main/java/at/bitfire/icsdroid/ui/CalendarListActivity.kt, app/src/main/java/at/bitfire/icsdroid/ui/EditCalendarActivity.kt, app/src/main/java/at/bitfire/icsdroid/ui/NotificationUtils.kt, app/src/main/res/layout/calendar_list_activity.xml, app/src/main/res/layout/edit_calendar.xml, app/src/main/res/values/strings.xml, build.gradle
I've created this first PR for #110, but there's no way to test it without migrating `AddCalendarActivity` first, at least. Should I join this PR with the update of this activity; merge this, and then create a new PR; or how should I continue? @rfc2822 
Note: I have removed the permission request for simplifying the view model.
Since `Subscription` doesn't have the `isSynced` field, `R.string.calendar_list_sync_disabled` is no longer displayed. We should remember to remove this string if finally no longer used.
The same happens for `R.string.edit_calendar_sync_this_calendar`.
=> Subscriptions in database: UI

app/src/main/java/at/bitfire/icsdroid/SyncWorker.kt, app/src/main/java/at/bitfire/icsdroid/db/AppDatabase.kt
Closes #120. I've chosen to implement it with extras since with `migrateLegacyCalendars` we have to move it to companion, and add all the parameters required, which at the end of the day is even dirtier.
=> Enabled migration on database creation

app/schemas/at.bitfire.icsdroid.db.AppDatabase/2.json, app/src/androidTest/java/at/bitfire/icsdroid/migration/CalendarToRoomMigrationTest.kt, app/src/main/java/at/bitfire/icsdroid/ProcessEventsTask.kt, app/src/main/java/at/bitfire/icsdroid/SyncWorker.kt, app/src/main/java/at/bitfire/icsdroid/calendar/LocalCalendar.kt, app/src/main/java/at/bitfire/icsdroid/calendar/LocalEvent.kt, app/src/main/java/at/bitfire/icsdroid/db/AppDatabase.kt, app/src/main/java/at/bitfire/icsdroid/db/CalendarCredentials.kt, app/src/main/java/at/bitfire/icsdroid/db/dao/SubscriptionsDao.kt, app/src/main/java/at/bitfire/icsdroid/db/entity/Subscription.kt, app/src/main/java/at/bitfire/icsdroid/ui/AddCalendarActivity.kt, app/src/main/java/at/bitfire/icsdroid/ui/AddCalendarDetailsFragment.kt, app/src/main/java/at/bitfire/icsdroid/ui/ColorPickerActivity.kt
=> Fix migrations

.github/workflows/test-dev.yml
Run CI tests on Large runners to get independent of the self-hosted runner, which shouldn't be used for public repos.
=> Large runners

app/build.gradle, build.gradle
Relevant changes are:
- Added primitive versions of the State API, allowing Int, Long, Float, and Double values to be tracked in State objects without incurring penalties for autoboxing. Use the new factory methods mutableIntState(Int), mutableFloatStateOf(Float), etc in order to use these. ([I48e43](https://android-review.googlesource.com/#/q/I48e438d0af15226217b77b2ba9a970c3219580bf))
We are not using any of them since we use LiveData in ViewModel.
Depends on #175
=> Upgraded Compose Dependencies

app/src/main/java/at/bitfire/icsdroid/ui/theme/Colors.kt
Looks like we just had a typo with the color
=> Fixed notification bar theming on dark mode

app/src/androidTest/java/at/bitfire/icsdroid/CalendarFetcherTest.kt, app/src/androidTest/java/at/bitfire/icsdroid/TestSettings.kt, app/src/androidTest/java/at/bitfire/icsdroid/migration/CalendarToRoomMigrationTest.kt, app/src/main/java/at/bitfire/icsdroid/CalendarFetcher.kt, app/src/main/java/at/bitfire/icsdroid/ProcessEventsTask.kt, app/src/main/java/at/bitfire/icsdroid/Settings.kt, app/src/main/java/at/bitfire/icsdroid/SyncWorker.kt, app/src/main/java/at/bitfire/icsdroid/db/dao/SubscriptionsDao.kt, app/src/main/java/at/bitfire/icsdroid/model/ValidationModel.kt
I've added a test for `Settings`, though if you don't find it necessary we can get rid of it.
=> Switch to compose state and kotlin flows - 1. iteration

app/build.gradle.kts, app/src/androidTest/java/at/bitfire/icsdroid/model/ValidationModelTest.kt, app/src/main/java/at/bitfire/icsdroid/model/CreateSubscriptionModel.kt, app/src/main/java/at/bitfire/icsdroid/model/CredentialsModel.kt, app/src/main/java/at/bitfire/icsdroid/model/EditSubscriptionModel.kt, app/src/main/java/at/bitfire/icsdroid/model/SubscriptionSettingsModel.kt, app/src/main/java/at/bitfire/icsdroid/model/ValidationModel.kt, app/src/main/java/at/bitfire/icsdroid/service/ComposableStartupService.kt, app/src/main/java/at/bitfire/icsdroid/ui/views/AddCalendarActivity.kt, app/src/main/java/at/bitfire/icsdroid/ui/views/CalendarListActivity.kt, app/src/main/java/at/bitfire/icsdroid/ui/views/EditCalendarActivity.kt, app/src/standard/java/at/bitfire/icsdroid/ui/DonateDialogService.kt, gradle/libs.versions.toml
Replacing LiveData with compose state and flows, will in the future hopefully prevent the issues that came with LiveData. Also it makes for easier integration with DAVx5.
This is the **2. Iteration** of the switch from LiveData to compose state and kotlin flows. See the [1. iteration here](https://github.com/bitfireAT/icsx5/pull/279).
The 1. Iteration took care of the Database Access Objects. It deprecated LiveData returning methods and added their respective Flow returning variants.
In this 2. iteration models and activities are rewritten, by replacing all LiveData usages in both models and activities,  **excluding**  any 1. iteration DAO changes, since this PR would grow too big otherwise.
The 3. iteration will take care of using the new Flow returning methods in DAOs and remove the …
=> Switch to compose state and kotlin flows - 2. iteration

app/src/main/java/at/bitfire/icsdroid/ui/views/EditCalendarActivity.kt
We were calling `setContent` twice, so the first one (which had the state receiver) was not being called.
=> [Severe] Editing/Deleting subscriptions doesn't update the UI

app/src/main/java/at/bitfire/icsdroid/model/EditCalendarModel.kt, app/src/main/java/at/bitfire/icsdroid/ui/screen/EditCalendarScreen.kt, app/src/main/java/at/bitfire/icsdroid/ui/views/CredentialsComposable.kt, app/src/main/java/at/bitfire/icsdroid/ui/views/EditCalendarActivity.kt, app/src/main/java/at/bitfire/icsdroid/ui/views/SubscriptionSettingsComposable.kt
As part of the switch to compose state and kotlin flows we also moved the code around as discussed in the guidelines for DAVx5. This PR applies these changes in the remaining EditCalendarActvivity.
- Extract composables
- handle view model creation in composables
- introduce a new EditCalendarModel, which 
- does the dirty view-model check 
- validation
- initializes other models (could maybe be rewritten to proper flow mapping and collection later on)
- leave intent logic in the activity
=> EditCalendarActvivity: Switch to compose state and kotlin flows

app/src/main/java/at/bitfire/icsdroid/PeriodicSyncWorker.kt
Fix workers piling up.
Switch back to replace aka cancel and reenqueue periodic workers.
- Switch back #REPLACE or rather [#CANCEL_AND_REENQUEUE](https://developer.android.com/reference/androidx/work/ExistingPeriodicWorkPolicy#CANCEL_AND_REENQUEUE) since thats the new name for #REPLACE.
- optimize imports
=> Fix workers piling up

app/src/main/java/at/bitfire/icsdroid/ui/views/EnterUrlComposable.kt
Stop the subscription form from covering the loading indicator #329 
- moved progress indicator bar into column
- adjusted padding
=> Stop subscription form covering the loading indicator

app/src/main/AndroidManifest.xml
Seems to be obsolete
- removed "requestLegacyExternalStorage=true" from the android manifest
=> Stop requesting legacy external storage

app/src/main/AndroidManifest.xml, app/src/main/java/at/bitfire/icsdroid/ui/views/AddCalendarActivity.kt
The keyboard covers the bottom bar when open. Probably caused because resizing is not enabled in the activity.
| Keyboard open | Keyboard closed |
|--------|--------|
| ![image](https://github.com/bitfireAT/icsx5/assets/12086466/887e96e6-800c-40f7-b292-e4d2019b355f) | ![image](https://github.com/bitfireAT/icsx5/assets/12086466/a035c7d5-2bcc-4f0b-98c0-bb038737d05e) | 
- Added `android:windowSoftInputMode="adjustResize"` to the manifest for `AddCalendarActivity`.
- Disabled `setDecorFitsSystemWindows` for `AddCalendarActivity`.
- Added `imePadding` to the contents of `AddCalendarActivity`.
=> Adjusted window resizing

app/build.gradle.kts, app/src/androidTest/java/at/bitfire/icsdroid/CalendarFetcherTest.kt, gradle/libs.versions.toml
Removes the need of Apache Commons
Depends on https://github.com/bitfireAT/ical4android/pull/156
=> Removed Commons dependency

app/build.gradle.kts, app/src/androidTest/java/at/bitfire/icsdroid/ComposableStartupServiceTest.kt, app/src/androidTest/java/at/bitfire/icsdroid/TestSettings.kt, app/src/main/java/at/bitfire/icsdroid/DataStore.kt, app/src/main/java/at/bitfire/icsdroid/Settings.kt, app/src/main/java/at/bitfire/icsdroid/model/SubscriptionsModel.kt, app/src/main/java/at/bitfire/icsdroid/service/ComposableStartupService.kt, app/src/main/java/at/bitfire/icsdroid/ui/InfoActivity.kt, app/src/main/java/at/bitfire/icsdroid/ui/screen/CalendarListScreen.kt, app/src/main/java/at/bitfire/icsdroid/ui/views/CalendarListActivity.kt, app/src/standard/java/at/bitfire/icsdroid/ui/DonateDialogService.kt, gradle/libs.versions.toml
The ose version of ICSx5 shows a donation dialog every once in a while, which does have a correct working donation button, but once you hide it, it doesn't pop up again, and can't be invoked in any other way. If the one in the info activity is pressed, the same is shown both in gplay and standard, which doesn't contain any donation button to comply with Google Play's policy.
This dialog should be the same as the one that pops up automatically in standard.
The preferences have been migrated to `DataStore` since otherwise there's no easy way to access them from outside the `DonateDialogService` for example.
There's a migration function in `SubscriptionsModel` even though I don't think it's even worth it for what it migrates.
Now in `InfoActivity` the services (`ComposableStartupService`) …
=> Donation dialog does not show button on standard

app/proguard-rules.pro
Fixed proguard warnings
- Disabled warnings for `com.github.erosb.jsonsKema.*`, not used by anything, it looks that it's incorrectly being detected.
- Disabled warnings for `org.jparsec.**` and `javax.cache.**`. Optional features not used by ICSx⁵.
Maybe we should report the issue with `com.github.erosb.jsonsKema` in ical4j, even though since it has to do with proguard, maybe Ben doesn't want to do a release. What do you think @rfc2822
=> Ignored warnings for unused classes

.github/workflows/test-dev.yml
`gradle/gradle-build-action` was replaced by `gradle/actions/setup-gradle` and we were still missing this migration.
Replaced `gradle/gradle-build-action@v3` by `gradle/actions/setup-gradle@v4`
=> Replaced deprecated gradle task

app/build.gradle.kts
As discussed for DAVx⁵, increasing to 35 should not have any implications, just make sure to keep WorkManager up to date.
Increased `compileSdk` and `targetSdk` to 35.
=> Increase SDK to 35

app/src/main/java/at/bitfire/icsdroid/AppAccount.kt, app/src/main/java/at/bitfire/icsdroid/model/SubscriptionsModel.kt
When collecting the sync interval setting flow the default value is emitted every time the app has a fresh start.
Send a first setting value for sync interval flow straight away buffered, such that we have the settingsvalue available straight away. This seems to prevent the use of the default value which is otherwise used.
=> Send setting value straight away

app/src/main/java/at/bitfire/icsdroid/ui/theme/Theme.kt, app/src/main/java/at/bitfire/icsdroid/ui/views/ActivityUtils.kt, app/src/main/java/at/bitfire/icsdroid/ui/views/AddCalendarActivity.kt, app/src/main/java/at/bitfire/icsdroid/ui/views/CalendarListActivity.kt, app/src/main/java/at/bitfire/icsdroid/ui/views/EditCalendarActivity.kt
Fixes #490
Simplified the whole edge-to-edge configuration. Now it's always "dark" for the status bar. Icons should always be white.
Skipped all the scrim thing because it just doesn't work well.
<details>
<summary>Light Mode</summary>
</details>
<details>
<summary>Dark Mode</summary>
</details>
=> Simplified edge-to-edge-configuration

app/src/main/java/at/bitfire/icsdroid/ui/views/EnterUrlComposable.kt
Makes the URL subscription text field bigger and enables user to scroll forward and backward.
- disable single line
- set maxLines to 8
For me that's enough to also be able to scroll the content of the text field
=> Bigger, scrollable URL subscription text field

app/src/main/java/at/bitfire/icsdroid/ui/views/EnterUrlComposable.kt
The paddings of the enter URL screen were not correct.
<details>
<summary>Screenshot</summary>
</details>
This is caused because we are adding two scaffolds at the same time, the inner one only for showing a snackbar.
- Disabled window insets for the innermost scaffold.
- Got rid of extra paddings for the tabs.
<details>
<summary>Screenshot</summary>
</details>
=> Fix paddings for the enter url screen

app/src/main/java/at/bitfire/icsdroid/ui/screen/AddCalendarScreen.kt
The IME "Go" button of the keyboard was doing nothing when entering a URL. This was because the index of the current page was incorrect.
- Changed current index for moving into the next page to `0` instead of `1`.
=> Fixed typo for IME action

app/src/main/java/at/bitfire/icsdroid/ui/views/AddCalendarActivity.kt
Replace the deprecated method `Intent.getParcelableExtra` with the implementation from `IntentCompat`, which uses the most adequate method depending on the current API level.
- Replace `Intent.getParcelableExtra` with `IntentCompat.getParcelableExtra`
=> Replace `getParcelableExtra` usage with `IntentCompat`

app/src/main/java/at/bitfire/icsdroid/db/dao/SubscriptionsDao.kt, app/src/main/java/at/bitfire/icsdroid/model/EditSubscriptionModel.kt, app/src/main/java/at/bitfire/icsdroid/ui/screen/EditCalendarScreen.kt
Collecting the flow only when needed, avoids continuous collection in the view model and might prevent the IllegalStateExceptions.
The proper way would be to avoid collecting the flow in the model at all, and only collect in the UI layer view, but that requires a bigger change, which we can do in a separate PR, if this does not fix the IllegalStateExceptions.
- Collect the flow only when needed, avoiding continuous collection in the view model.
- Use .firstOrNull() to get the current value once inside the coroutine of updateSubscription and removeSubscriptoin.
- split subscription into a separate flow from subscriptionWithCredential for clarity
=> Collect flow in viewModel only when needed

app/build.gradle.kts, app/src/androidTest/java/at/bitfire/icsdroid/BaseSyncWorkerTest.kt, app/src/androidTest/java/at/bitfire/icsdroid/HiltTestRunner.kt, app/src/androidTest/java/at/bitfire/icsdroid/TestSyncWorker.kt, app/src/main/AndroidManifest.xml, app/src/main/java/at/bitfire/icsdroid/App.kt, app/src/main/java/at/bitfire/icsdroid/BaseSyncWorker.kt, app/src/main/java/at/bitfire/icsdroid/PeriodicSyncWorker.kt, app/src/main/java/at/bitfire/icsdroid/ProcessEventsTask.kt, app/src/main/java/at/bitfire/icsdroid/SyncWorker.kt, app/src/main/java/at/bitfire/icsdroid/db/AppDatabase.kt, app/src/main/java/at/bitfire/icsdroid/model/CreateSubscriptionModel.kt, app/src/main/java/at/bitfire/icsdroid/model/CredentialsModel.kt, app/src/main/java/at/bitfire/icsdroid/model/EditSubscriptionModel.kt, app/src/main/java/at/bitfire/icsdroid/model/SubscriptionSettingsModel.kt, app/src/main/java/at/bitfire/icsdroid/model/SubscriptionsModel.kt, app/src/main/java/at/bitfire/icsdroid/model/ThemeModel.kt, app/src/main/java/at/bitfire/icsdroid/model/ValidationModel.kt, app/src/main/java/at/bitfire/icsdroid/ui/screen/EditCalendarScreen.kt, app/src/main/java/at/bitfire/icsdroid/ui/theme/Theme.kt, app/src/main/java/at/bitfire/icsdroid/ui/views/AddCalendarActivity.kt, app/src/main/java/at/bitfire/icsdroid/ui/views/CalendarListActivity.kt, app/src/main/java/at/bitfire/icsdroid/ui/views/EditCalendarActivity.kt, build.gradle.kts, gradle/libs.versions.toml
Using hilt for DI will make the ICSx5 code base resemble more the one of DAVx5 and ease the integration.  
- integrated hilt
- use hilt for app database injection
- use hilt for workers
- use hilt in most viewmodels
- make BaseSyncWorker abstract
- adapt tests
**Note**
I consciously tried not to let the PR grow too big, so we can address 
- linting
- copyright comments 
- fixing EditCalendarModel depending on other view models 
in a new PR. Everything should still be in a working state of course, however.
=> Use Hilt for DI

app/src/main/java/at/bitfire/icsdroid/ui/InfoActivity.kt
When migrating to Hilt, we forgot annotating the `InfoActivity` class.
- Added missing annotation
=> Fix about app dialog

app/src/main/java/at/bitfire/icsdroid/ui/screen/SubscriptionsScreen.kt
Before #640 we were calling `checkSyncSettings` in the activity's [`onResume`](https://github.com/bitfireAT/icsx5/pull/640/files#diff-25f544a56fb9bce003222f372d4bc69760e4da19e90a75373d0ab891cfea48f7L123-L126) function.
However, after the PR, it was replaced by a simple `LaunchedEffect`. It should be `LifecycleResumeEffect` to match the original behavior.
Moved `checkSyncSettings` to a `LifecycleResumeEffect`.
=> Run `checkSyncSettings` on lifecycle resume

.github/dependabot.yml
Followed the other bitfire respos with the Dependabot grouping feature.
- Added groups
=> Enable grouping just like the other repos

app/src/main/java/at/bitfire/icsdroid/AppHttpClient.kt
Timeouts were not being applied correctly / at all.
- use ktor plugin to apply the timeouts
- don't set timeout for okhttp directly 
https://ktor.io/docs/client-timeout.html
=> Fix timeouts not being applied

app/src/main/java/at/bitfire/icsdroid/AppHttpClient.kt
~We are _trying_ to disable redirection following in the engine config. We don't even want to disable redirection, so remove that line.~
We do have to disable redirection, it's handled by `CalendarFetcher`. Following [the docs](https://ktor.io/docs/client-redirect.html), this is the way to disable it so it can be handled by it.
- ~Remove the redirection disable in engine config.~
- Move the redirection disabling
- Add a comment to make sure we don't get confused again in the future.
=> Globally disable follow redirects

app/src/main/java/at/bitfire/icsdroid/ui/screen/EditSubscriptionScreen.kt
In `EditSubscriptionScreen` only: Keyboard overlays bottom part of screen (can't scroll to show content below keyboard).
- add `imePadding()` to scaffold
=> Add imePadding in EditSubscriptionScreen.kt
