app/src/main/java/at/bitfire/icsdroid/PermissionUtils.kt
app/src/main/java/at/bitfire/icsdroid/ui/AddCalendarActivity.kt
app/src/main/java/at/bitfire/icsdroid/ui/CalendarListActivity.kt

Use new permissions request method (closes bitfireAT/icsx5#6)

use new permissions request method (closes bitfireAT/icsx5#6)

---

app/build.gradle

raise API level to 31, Android 12 (closes bitfireAT/icsx5#5)

bump version to 1.9.4-beta.1

---

app/src/main/AndroidManifest.xml
app/src/main/java/at/bitfire/icsdroid/CalendarFetcher.kt
app/src/main/java/at/bitfire/icsdroid/HttpUtils.kt
app/src/main/java/at/bitfire/icsdroid/ProcessEventsTask.kt
app/src/main/java/at/bitfire/icsdroid/ui/AddCalendarEnterUrlFragment.kt
app/src/main/java/at/bitfire/icsdroid/ui/AddCalendarValidationFragment.kt
app/src/main/java/at/bitfire/icsdroid/ui/CredentialsFragment.kt
app/src/main/java/at/bitfire/icsdroid/ui/EditCalendarActivity.kt
app/src/main/java/at/bitfire/icsdroid/ui/ResourceInfo.kt
app/src/main/res/layout/add_calendar_enter_url.xml
app/src/main/res/values/strings.xml

WIP: Should use Uri objects everywhere instead of URL

Move from file ur is to saf (closes bitfireAT/icsx5#2)

---

app/src/main/java/at/bitfire/icsdroid/CalendarFetcher.kt
app/src/main/java/at/bitfire/icsdroid/ui/AddCalendarEnterUrlFragment.kt
app/src/main/res/values/strings.xml

Gives a proper error message when a synced file is deleted (closes #19)

error message when a synced file is deleted (closes #19)

---

app/src/main/java/at/bitfire/icsdroid/ui/AddCalendarDetailsFragment.kt
app/src/main/java/at/bitfire/icsdroid/ui/AddCalendarEnterUrlFragment.kt
app/src/main/java/at/bitfire/icsdroid/ui/AddCalendarValidationFragment.kt
app/src/main/java/at/bitfire/icsdroid/ui/EditCalendarActivity.kt

Fixes auth toggle being disabled, that is shown when adding http or https subscriptions.
We should not set it's state while validating the input URI ...

fix auth toggle (closes #35)

---

app/src/main/java/at/bitfire/icsdroid/ui/InfoActivity.kt

Fixed url launching

---

.github/workflows/dependent-issues.yml

Signed-off-by: Arnau Mora <arnyminer.z@gmail.com>

Added dependent issues

---

README.md

Added translations page link

---

app/src/main/java/at/bitfire/icsdroid/ui/EditCalendarActivity.kt

Fixed back handler

---

app/src/main/java/at/bitfire/icsdroid/ui/TitleColorFragment.kt

Configured the edit text:
- Made it single line
- Changed action button to "Done"
- Changed keyboard type to numbers

Configured default alarm dialog to improve UX

---

app/build.gradle
app/src/main/AndroidManifest.xml
build.gradle
gradle.properties

- remove Locator dependency (closes #153)
- disable per-app language preferences for now

Improve build speed with gradle configuration cache

---

app/src/main/java/at/bitfire/icsdroid/ui/AddCalendarDetailsFragment.kt
app/src/main/java/at/bitfire/icsdroid/ui/AddCalendarEnterUrlFragment.kt

I was continuously getting a `NullPointerException` here. That fixes it.

Fixed NullPointerException

---

README.md

See https://github.com/bitfireAT/davx5/issues/310

Replaced Twitter link with Mastodon

---

build.gradle

No relevant changes in the changelog: https://developer.android.com/build/releases/gradle-plugin#agp-8-0-2

Upgraded AGP to 8.0.2

---

app/build.gradle
build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties
settings.gradle

No relevant changelog: https://developer.android.com/build/releases/gradle-plugin#8-1-0

Upgraded AGP, Gradle, dependencies and deprecations

---

app/src/main/AndroidManifest.xml
app/src/main/java/at/bitfire/icsdroid/ui/views/CalendarListActivity.kt

Should solve #215, though I'm not sure if we will have any problems with the `REQUEST_IGNORE_BATTERY_OPTIMIZATIONS` permission. @devvv4ever do you know if we need any verification for that?

Improved battery optimization card

---

app/src/main/java/at/bitfire/icsdroid/ui/views/CalendarListActivity.kt
app/src/standard/java/at/bitfire/icsdroid/ui/DonateDialogService.kt

Moved service initialization to Compose

---

app/src/main/java/at/bitfire/icsdroid/PeriodicSyncWorker.kt

I don't see any issues with just straight up using the new UPDATE policy.

Change existing work policy to UPDATE

---

app/src/androidTest/java/at/bitfire/icsdroid/CalendarFetcherTest.kt
app/src/androidTest/java/at/bitfire/icsdroid/TestSettings.kt
app/src/androidTest/java/at/bitfire/icsdroid/migration/CalendarToRoomMigrationTest.kt
app/src/main/java/at/bitfire/icsdroid/CalendarFetcher.kt
app/src/main/java/at/bitfire/icsdroid/ProcessEventsTask.kt
app/src/main/java/at/bitfire/icsdroid/Settings.kt
app/src/main/java/at/bitfire/icsdroid/SyncWorker.kt
app/src/main/java/at/bitfire/icsdroid/db/dao/SubscriptionsDao.kt
app/src/main/java/at/bitfire/icsdroid/model/ValidationModel.kt

Adds the original PR back https://github.com/bitfireAT/icsx5/issues/278

Switch to compose state and kotlin flows - 1. iteration

---

app/src/main/res/values-de/strings.xml
app/src/main/res/values-ja/strings.xml

I've created the PR again since it got a bit messed up.

New German and Japanese translations

---

app/src/main/java/at/bitfire/icsdroid/AppAccount.kt
app/src/main/java/at/bitfire/icsdroid/model/CreateSubscriptionModel.kt
app/src/main/java/at/bitfire/icsdroid/model/CredentialsModel.kt
app/src/main/java/at/bitfire/icsdroid/model/EditSubscriptionModel.kt
app/src/main/java/at/bitfire/icsdroid/model/SubscriptionSettingsModel.kt
app/src/main/java/at/bitfire/icsdroid/model/SubscriptionsModel.kt
app/src/main/java/at/bitfire/icsdroid/ui/screen/AddCalendarScreen.kt
app/src/main/java/at/bitfire/icsdroid/ui/screen/CalendarListScreen.kt
app/src/main/java/at/bitfire/icsdroid/ui/views/AddCalendarActivity.kt
app/src/main/java/at/bitfire/icsdroid/ui/views/CalendarListActivity.kt
app/src/main/java/at/bitfire/icsdroid/ui/views/EditCalendarActivity.kt

Switch to compose state and kotlin flows - 4. iteration

---

app/src/main/java/at/bitfire/icsdroid/ProcessEventsTask.kt

See full discussion in #248, follow-up in #327
- Added VAlarm both to the event in question and exceptions.

Added alarms to exceptions

---

app/build.gradle.kts
build.gradle.kts
gradle/libs.versions.toml

Upgrade dependencies
Followed the steps at https://android-developers.googleblog.com/2024/04/jetpack-compose-compiler-moving-to-kotlin-repository.html
Closes #331
Closes #365

Upgraded Kotlin to 2.0.0 and KSP to 1.0.22

---

app/src/main/res/values-ca/strings.xml
app/src/main/res/values-cs/strings.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-gl/strings.xml
app/src/main/res/values-ja/strings.xml
app/src/main/res/values-nl/strings.xml
app/src/main/res/values-pl-rPL/strings.xml
app/src/main/res/values-pt-rBR/strings.xml
app/src/main/res/values-ro/strings.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-zh/strings.xml

Added missing translations
Fetched all the new translations from Transifex.

Fetched translations from Transifex

---

app/src/main/res/values-ca/strings.xml

Fetch new translations from Transifex
Just a single translation for Catalan, but there it is.

Fetch new translations

---

app/src/main/java/at/bitfire/icsdroid/ui/partials/ActionCard.kt
app/src/main/res/values/strings.xml

See #270
Reduced text on cards, moved action button to top right, and made the whole card clickable.

Simplify UI

---

app/src/main/res/values-ca/strings.xml
app/src/main/res/values-da/strings.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-gl/strings.xml
app/src/main/res/values-hu/strings.xml
app/src/main/res/values-ja/strings.xml
app/src/main/res/values-nl/strings.xml
app/src/main/res/values-pl-rPL/strings.xml
app/src/main/res/values-pt-rBR/strings.xml
app/src/main/res/values-pt-rPT/strings.xml
app/src/main/res/values-ro/strings.xml
app/src/main/res/values-ru-rUA/strings.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-si/strings.xml
app/src/main/res/values-zh/strings.xml

Update translations from Transifex.
Fetched all the updated translations from Transifex.

Translations from Transifex

---

README.md

Still had the old ICSx5 forums link.
Update link for discussing help, ideas and bugreports from forum to github discussions.

Update discussions link

---

app/src/main/java/at/bitfire/icsdroid/ui/InfoActivity.kt

There are some small lint warnings
Fixed the ones I've found.

Fix lint warnings

---

README.md

To update dead transifex link.
- Update dead transifex link

Update dead transifex link
